### ISSUE TITLE
Mailserver / iRedMail

### ISSUE THREAD

**Issue by joubertredrat** [kahun/awesome-sysadmin#227]
Free, Open Source Email Server Solution

http://www.iredmail.org/

**Comment by n1trux** [comment]
I added your suggestion to my new repo ([n1trux/awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin/)) and would very like you to consider adding suggestions to my repo in the future, too.

Thanks for (involuntarily ;) contributing!

**Comment by joubertredrat** [comment]
Repo is died :|
