### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by pierreozoux** [kahun/awesome-sysadmin#261]
Hi,

I'm just wodering, what is the status of this project?

Thanks,

Pierre

**Comment by falzm** [comment]
Last merge on Oct 10 2014, I guess the status is pretty clear to me...

**Comment by leehambley** [comment]
Don't feed the trolls, there's a perfectly good Git log, and the Github "Pulse" tab, and he ignored both.

**Comment by pierreozoux** [comment]
That's why I'm asking, if not, I don't ask.

So it's an opportunity for the owner to say, 'sorry, I didn't have time lately, if you want I give you push access'.. I don't know.

But then, what do we do? I think it is a nice project, and it is sad to let it like this. Do we fork it?

**Comment by leehambley** [comment]
Frankly when the project started accepting all manner of half-baked tools into it's "Curated list" it stopped being useful and was superseded by better quality lists.

**Comment by icovada** [comment]
You can fork whatever you like without approval from anyone.

I don't think that a couple months without updates in a list of software means that the project is dead.

**Comment by kahun** [comment]
Sorry, I am a little busy right now but the project is not dead

**Comment by pierreozoux** [comment]
@leehambley feel free to PR :) like [this](https://github.com/kahun/awesome-sysadmin/pulls?q=is%3Apr+remove+is%3Aclosed)

@kahun thanks!

Have a nice day!

Pierre

**Comment by n1trux** [comment]
I started a new [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) repo a while ago and would like to address @leehambley's concerns about half-baked tools. I'd really appreciate contributors who may help to sort out the tools which aren't awesome.

There is a [gitter chat room](https://gitter.im/n1trux/awesome-sysadmin) where contributors could discuss stuff which isn't awesome and should be removed.

When @kahun isn't busy anymore, I can create a PR or he can work on the new repository, as he pleases.

**Comment by leehambley** [comment]
The problem is from my point of view, that the list started as "a curated list of awesome sysadmin tools", and then became a list of everything you might reasonably find on a *nix machine, and subsequently useless. :(

**Comment by n1trux** [comment]
@leehambley yes, that's my point of view, too – so I might want to condense the list a lot and only include a few select softwares for each task. But I need help with this, see the gitter chat for further information.

If you think an item on the list is not awesome, feel free to create a PR.
