### ISSUE TITLE
No longer being updated

### ISSUE THREAD

**Issue by ardichoke** [kahun/awesome-sysadmin#401]
It looks like @kahun has not merged any Pull Requests for almost a year. Seems like this (very useful) resource has been abandoned. Should this be forked by someone who has the time and desire to actively manage it?

**Comment by aaronrl** [comment]
@n1trux has forked this repo and has been responsive on all PRs I've seen submitted to the fork.

https://github.com/n1trux/awesome-sysadmin

**Comment by pratt1305** [comment]
I Agree with @ardichoke Someone Should Manage IT ...............

**Comment by ardichoke** [comment]
Thanks @aaronrl, I've updated my bookmark accordingly.

I had been thinking about forking the list and turning it into a community updated website.... because I'm looking for a project with which to learn Jekyll...

**Comment by timkofu** [comment]
I've update my bookmark as well. Thanks.

**Comment by n1trux** [comment]
@ardichoke we [had this discussion already on sindresorhus's awesome repo](https://github.com/sindresorhus/awesome/issues/427) and somebody did make a site to search in the awesome lists:

https://awesomelists.top/

You may contribute to that:

https://github.com/lockys/AwesomeSearch

It's made in Ruby, not jekyll though. However I think you can adapt a Jekyll solution with the help of the provided JSON format.

**Comment by timkofu** [comment]
@n1trux Thanks for sharing awesomesearch 👍

**Comment by StanBright** [comment]
OK, I've linked https://sysadmin.libhunt.com to https://github.com/n1trux/awesome-sysadmin now. 

Good job, @n1trux

**Comment by Raboo** [comment]
Why don't we create a github organization, perhaps not limited to only awesome sysadmin, but allowing all the other awesome collections to join.
That way we can have multiple administrators merging pull requests and maintaining the lists.

**Comment by teadur** [comment]
I like the idea, not really big contributor here but having it depend on one person is risky like we see from this repo.

+1 for Awesome Org

**Comment by JokerQyou** [comment]
Love the idea with awesome organization. Did someone propose this to the meta-awesome (https://github.com/sindresorhus/awesome) repo?
